export const DEFAULT_PORTFOLIO_SAMPLE_TICKER = "2330.TW";
export const DEFAULT_PORTFOLIO_SECONDARY_SAMPLE_TICKER = "0050.TW";
export const DEFAULT_PORTFOLIO_WHAT_IF_TICKER = DEFAULT_PORTFOLIO_SAMPLE_TICKER;
